sudo: required
language: go
go:
  - 1.x
services:
  - docker
notifications:
  email: false

jobs:
  include:
    - stage: Mandatory build
      install:
        - go get -t ./...
      script:
        - go build main.go
      after_success:
        - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o ~/semantic-release && chmod +x ~/semantic-release
        - go get github.com/tcnksm/ghr
        - ./release.sh
      deploy:
        - provider: script
          script: ./ci/choco/deploy.sh
          skip_cleanup: true
          on:
            tags: true
            branch: master
